CONTAINER AINODE_FASTNOISE
{
    NAME ainode_FastNoise;

    GROUP C4DAI_FASTNOISE_MAIN_GRP
    {
        DEFAULT 1;

        AIPARAM C4DAIP_FASTNOISE_NOISE_TYPE {}
        AIPARAM C4DAIP_FASTNOISE_SEED {}
        AIPARAM C4DAIP_FASTNOISE_FREQUENCY {}
    }

    GROUP C4DAI_FASTNOISE_FRACTAL_GRP
    {
        DEFAULT 1;

        AIPARAM C4DAIP_FASTNOISE_FRACTAL_TYPE {}
        AIPARAM C4DAIP_FASTNOISE_FRACTAL_OCTAVES {}
        AIPARAM C4DAIP_FASTNOISE_FRACTAL_LACUNARITY {}
        AIPARAM C4DAIP_FASTNOISE_FRACTAL_GAIN {}
    }

    GROUP C4DAI_FASTNOISE_CELLULAR_GRP
    {
        DEFAULT 1;

        AIPARAM C4DAIP_FASTNOISE_CELLULAR_DISTANCE_FUNCTION {}
        AIPARAM C4DAIP_FASTNOISE_CELLULAR_RETURN_TYPE {}
        AIPARAM C4DAIP_FASTNOISE_CELLULAR_JITTER {}
    }

    GROUP C4DAI_FASTNOISE_WARP_GRP
    {
        DEFAULT 1;

        AIPARAM C4DAIP_FASTNOISE_POSITION_WARP {}
        AIPARAM C4DAIP_FASTNOISE_POSITION_WARP_AMPLITUDE {}
    }

    GROUP C4DAI_FASTNOISE_COORDINATES_GRP
    {
        AIPARAM C4DAIP_FASTNOISE_SPACE {}
        AIPARAM C4DAIP_FASTNOISE_OFFSET {}
        AIPARAM C4DAIP_FASTNOISE_SCALE {}
        AIPARAM C4DAIP_FASTNOISE_ROTATE {}
        AIPARAM C4DAIP_FASTNOISE_P {}
        SEPARATOR {LINE;}
        STRING C4DAIP_FASTNOISE_INFO { READONLY; ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; }
    }
}