#ifndef _ainode_FastNoise_h_
#define _ainode_FastNoise_h_

enum
{
   C4DAI_FASTNOISE_MAIN_GRP                           = 2001,
   C4DAI_FASTNOISE_FRACTAL_GRP,
   C4DAI_FASTNOISE_CELLULAR_GRP,
   C4DAI_FASTNOISE_WARP_GRP,
   C4DAI_FASTNOISE_COORDINATES_GRP,

   C4DAIP_FASTNOISE_SPACE                             = 1512891157,
   C4DAIP_FASTNOISE_OFFSET                            = 1445995814,
   C4DAIP_FASTNOISE_SCALE                             = 1513358041,
   C4DAIP_FASTNOISE_ROTATE                            = 1574559278,
   C4DAIP_FASTNOISE_P                                 = 883458161,
   C4DAIP_FASTNOISE_NOISE_TYPE                        = 1716181406,
   C4DAIP_FASTNOISE_SEED                              = 436308608,
   C4DAIP_FASTNOISE_FREQUENCY                         = 1497661839,
   C4DAIP_FASTNOISE_FRACTAL_TYPE                      = 572136125,
   C4DAIP_FASTNOISE_FRACTAL_OCTAVES                   = 2123826160,
   C4DAIP_FASTNOISE_FRACTAL_LACUNARITY                = 662413481,
   C4DAIP_FASTNOISE_FRACTAL_GAIN                      = 571642586,
   C4DAIP_FASTNOISE_CELLULAR_DISTANCE_FUNCTION        = 932861762,
   C4DAIP_FASTNOISE_CELLULAR_RETURN_TYPE              = 209607469,
   C4DAIP_FASTNOISE_CELLULAR_JITTER                   = 762316612,
   C4DAIP_FASTNOISE_POSITION_WARP                     = 814005171,
   C4DAIP_FASTNOISE_POSITION_WARP_AMPLITUDE           = 1316124977,
   C4DAIP_FASTNOISE_NAME                              = 436492384,
   C4DAIP_FASTNOISE_INFO                              = 436658133,

   C4DAIP_FASTNOISE_SPACE__WORLD                      = 0,
   C4DAIP_FASTNOISE_SPACE__OBJECT                     = 1,
   C4DAIP_FASTNOISE_SPACE__PREF                       = 2,
   C4DAIP_FASTNOISE_SPACE__UV                         = 3,

   C4DAIP_FASTNOISE_NOISE_TYPE__VALUE                 = 0,
   C4DAIP_FASTNOISE_NOISE_TYPE__VALUE_FRACTAL         = 1,
   C4DAIP_FASTNOISE_NOISE_TYPE__PERLIN                = 2,
   C4DAIP_FASTNOISE_NOISE_TYPE__PERLIN_FRACTAL        = 3,
   C4DAIP_FASTNOISE_NOISE_TYPE__SIMPLEX               = 4,
   C4DAIP_FASTNOISE_NOISE_TYPE__SIMPLEX_FRACTAL       = 5,
   C4DAIP_FASTNOISE_NOISE_TYPE__CELLULAR              = 6,
   C4DAIP_FASTNOISE_NOISE_TYPE__WHITE_NOISE           = 7,
   C4DAIP_FASTNOISE_NOISE_TYPE__CUBIC                 = 8,
   C4DAIP_FASTNOISE_NOISE_TYPE__CUBIC_FRACTAL         = 9,

   C4DAIP_FASTNOISE_FRACTAL_TYPE__FBM                 = 0,
   C4DAIP_FASTNOISE_FRACTAL_TYPE__BILLOW              = 1,
   C4DAIP_FASTNOISE_FRACTAL_TYPE__RIGID_MULTI         = 2,

   C4DAIP_FASTNOISE_CELLULAR_DISTANCE_FUNCTION__EUCLIDEAN = 0,
   C4DAIP_FASTNOISE_CELLULAR_DISTANCE_FUNCTION__MANHATTAN = 1,
   C4DAIP_FASTNOISE_CELLULAR_DISTANCE_FUNCTION__NATURAL = 2,

   C4DAIP_FASTNOISE_CELLULAR_RETURN_TYPE__CELLVALUE   = 0,
   C4DAIP_FASTNOISE_CELLULAR_RETURN_TYPE__NOISELOOKUP = 1,
   C4DAIP_FASTNOISE_CELLULAR_RETURN_TYPE__DISTANCE    = 2,
   C4DAIP_FASTNOISE_CELLULAR_RETURN_TYPE__DISTANCE2   = 3,
   C4DAIP_FASTNOISE_CELLULAR_RETURN_TYPE__DISTANCE2ADD = 4,
   C4DAIP_FASTNOISE_CELLULAR_RETURN_TYPE__DISTANCE2SUB = 5,
   C4DAIP_FASTNOISE_CELLULAR_RETURN_TYPE__DISTANCE2MUL = 6,
   C4DAIP_FASTNOISE_CELLULAR_RETURN_TYPE__DISTANCE2DIV = 7,

   C4DAIP_FASTNOISE_POSITION_WARP__OFF                = 0,
   C4DAIP_FASTNOISE_POSITION_WARP__ON                 = 1,
   C4DAIP_FASTNOISE_POSITION_WARP__FRACTAL            = 2,
};

#endif

